-- Associazioni gestibili da master/super_user.

CREATE TABLE IF NOT EXISTS public.associazioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT associazioni_nome_not_blank CHECK (length(trim(nome)) > 0),
    CONSTRAINT associazioni_nome_unique UNIQUE (nome)
);

ALTER TABLE public.associazioni ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "associazioni_select_authenticated" ON public.associazioni;
CREATE POLICY "associazioni_select_authenticated"
    ON public.associazioni
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "associazioni_insert_master" ON public.associazioni;
CREATE POLICY "associazioni_insert_master"
    ON public.associazioni
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_master());

DROP POLICY IF EXISTS "associazioni_delete_master" ON public.associazioni;
CREATE POLICY "associazioni_delete_master"
    ON public.associazioni
    FOR DELETE
    TO authenticated
    USING (public.is_master());

GRANT SELECT, INSERT, DELETE ON public.associazioni TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.associazioni_id_seq TO authenticated;

INSERT INTO public.associazioni (nome)
VALUES
    ('G.C. Massa di Somma'),
    ('G.C. Cercola'),
    ('Cobra 2'),
    ('G.C. Sant''Anastasia'),
    ('Save Me'),
    ('NVPC Pomigliano'),
    ('COPCSV Pomigliano')
ON CONFLICT (nome) DO NOTHING;
